---
title: "Multimerger Case Study: Vibrio Cholera in Argentina"
output: rmarkdown::html_document
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4, tibble.print_max = 4)
```

Load Packages
```{r}
library(MMCTime)
library(ggplot2)
library(ape)
library(ggtree)
library(posterior)
library(reshape2)
library(patchwork)

set.seed(12343)
run_mcmc <- F
```

Preprocess the tree from https://microreact.org/project/VAZD_K0kZ 
```{r}
#Xavier's Script
tree <- read.tree('tree.nwk')
data <- read.csv('data.csv')

tree$edge.length<-tree$edge.length*7556#from legend of Fig2
dates<-data$year+(data$month-1)/12+(data$day-1)/365
names(dates)<-data$id

#Subset to argentina only and drop missing dates
w<-which(data$country!='Argentina'|is.na(dates))
tree <- drop.tip(tree,data$id[w])

tree$edge.length<-round(tree$edge.length)
dates <- dates[tree$tip.label]
```
Plot the mutation scaled phylogeny
```{r, out.width="100%"}
ggtree(tree) + theme_tree2()
```

Run MMCTime under Modified Beta, as well as under Kingman for comparison
```{r, eval=run_mcmc}
res_kmb <- mmctime(tree, dates, n_draws=1e3L, thin=3e3L, n_chain=4, model="km_beta", verbose=F, fix_root=T)
saveRDS(res_kmb, "res_kmb.rds")
res_km <- mmctime(tree, dates, n_draws=1e3L, thin=3e3L, n_chain=4, model="kingman", verbose=F, fix_root=T)
saveRDS(res_km, "res_km.rds")
```
Or load a saved run
```{r, eval=!run_mcmc}
res_kmb <- readRDS("res_kmb.rds")
res_km <- readRDS("res_km.rds")
```

Inspect the posterior summaries for modified beta
```{r}
print(res_kmb$summaries, n=20)
```
Inspect the posterior summaries for beta
```{r}
print(res_kmb$summaries, n=20)
```
Plot a summary tree
```{r, out.width="100%",eval=F}
p <- plot_densiCI(res_kmb, n_samp=250, mrsd=max(dates))
pdf("../manuscript_figs/vibrio_densi_mm.pdf",8,8)
p
dev.off()
p
```

```{r, out.width="100%",eval=F}
p <- plot_densiCI(res_km, n_samp=250, mrsd=max(dates))
pdf("../manuscript_figs/vibrio_densi_km.pdf",8,8)
p
dev.off()
p
```
```{r,eval=T,out.width="100%"}
p <- plot_mm_tree(sample_timetree(res_kmb,9))
pdf("../manuscript_figs/vibrio_mm_ps.pdf", 8, 8)
p
dev.off()
p
```
Modified beta posterior draws
```{r,eval=T,out.width="100%"}
p <- plot_mm_tree(sample_timetree(res_km,9))
pdf("../manuscript_figs/vibrio_km_ps.pdf", 8, 8)
p
dev.off()
p
```
```{r,eval=T,out.width="100%"}
p <- plot_mm_tree(sample_timetree(res_beta,9))
pdf("../manuscript_figs/beta_ps.pdf", 8, 8)
p
dev.off()
p
```

```{r, out.width="100%"}
p <- plot_pars(res_kmb)
pdf("../manuscript_figs/vibrio_pars_mm.pdf",8,8)
p
dev.off()
p
```
Inspect traces
```{r, out.width="100%"}
p <- plot_traces(res_kmb)
pdf("../manuscript_figs/vibrio_trace_mm.pdf",8,8)
p
dev.off()
p
```
```{r, out.width="100%"}
thm1 <-function() theme(axis.title.x=element_blank(),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank(), 
    axis.text.x=element_text(size=rel(0.7), angle = 45, hjust=1),
    aspect.ratio=1,
    plot.margin = margin(0, 0, 0, 0, "cm"),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    axis.line = element_line(size=rel(0.2), colour = "grey80"),
    plot.title = element_text(hjust = 0.5,size=rel(1.0)))

tmp1 <- cbind(res_kmb$draws[,c("mu", "sigma")],1)
colnames(tmp1) <- c("mu", "sigma", "prior")
tmp2 <- cbind(res_km$draws[,c("mu", "sigma")],2)
colnames(tmp2) <- c("mu", "sigma", "prior")

mut_draws <- rbind(tmp1,tmp2)
mut_draws$prior <- factor(mut_draws$prior)

p <- ggplot(melt(mut_draws), aes(x=value,y=variable, fill=prior)) + 
    geom_boxplot() + 
    theme_minimal() + 
    thm1()

pdf("../manuscript_figs/vibrio_mut.pdf",8,8)
p
dev.off()
p
```