---
title: "Multimerger Timing Simulation Analysis"
output: rmarkdown::html_document
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4, tibble.print_max = 4)
```

Load Packages
```{r}
library(MMCTime)
library(ggplot2)
library(ape)
library(posterior)
library(reshape2)
library(patchwork)
```

Ingest Data
```{r}
mut_sets <- 3L
set_size <- 3L*48L
n_tips <- 200

root_n <- "t_201"
height_n <- "rel_height"
len_n <- "rel_length"

alphas <-seq(from=.01, to=.99, length.out=set_size)
f <- function(clock, run_idx)
{
    res<-readRDS(paste0("./mut",clock,"/ana_out/res_", run_idx, ".rds"))
    tmp <- as.data.frame(res$summaries[,c("variable", "median", "q5", "q95", "rhat", "ess_bulk")])
    tmp$run_idx <- run_idx
    tmp$clock <- clock

    g <- function(x)
    {
        y <- node.depth.edgelength(read.tree(paste0("./gt/tree_",x,".nwk")))
        return(max(y))
    }

    g_len <- function(x)
    {
        y <- read.tree(paste0("./gt/tree_",x,".nwk"))$edge.length
        return(sum(y))
    }


    gt_len <- g_len(run_idx)
    gt_h <- g(run_idx)

    tmp[tmp$variable == root_n, c("q5","median","q95")] <- (tmp[tmp$variable == root_n, c("q5","median","q95")]-gt_h)/gt_h
    tmp[tmp$variable == root_n,"variable"] = height_n

    tmp[tmp$variable == "tree_length", c("q5","median","q95")] <- (tmp[tmp$variable == "tree_length", c("q5","median","q95")]-gt_len)/gt_len
    tmp[tmp$variable == "tree_length", "variable"] = len_n

    return(tmp)
}

dfs <- do.call(rbind,lapply(1L:mut_sets,
    function(i) do.call(rbind, lapply(1L:set_size,
            function(j) f(i,j)))))
```

Plot Stuff
```{r}
sum_plt <- function(df)
{
    conv_df <- data.frame(run_idx = rep(1L:set_size, mut_sets), clock= do.call(c,lapply(1L:mut_sets, function (x) rep(x, set_size))))
    conv_df$conv <- apply(conv_df, 1, function(x)  all((df[which((df$run_idx == x[1]) & (df$clock == x[2])),]$ess_bulk>200)) && 
        all(df[which((df$run_idx == x[1]) & (df$clock == x[2])),]$rhat < 1.05))
    conv_df$variable <- height_n
    conv_df <- conv_df[!conv_df$conv, ]
    
    vns <- c("alpha", "nu","omega","mu", len_n, height_n)

    allDf <- df[df$variable %in% vns, ]
    gt_df <- data.frame(clock = c(rep(1, set_size), rep(2, set_size), rep(3, set_size)),
        run_idx = rep(1:set_size,mut_sets),
        alpha=rep(alphas,mut_sets),
        nu=rep(1/10, mut_sets*set_size),
        mu=c(rep(3, set_size),rep(6, set_size),rep(12, set_size)),
        omega=c(rep(1, set_size),rep(2, set_size),rep(4, set_size)),
        rel_length=rep(0.0, mut_sets*set_size),
        rel_height=rep(0.0, mut_sets*set_size)
        )
    gt_df <- melt(gt_df, measure.vars=vns)
    
    gt_df$variable <- factor(gt_df$variable, levels=vns)
    allDf$variable <- factor(allDf$variable, levels=vns)
    conv_df$variable <- factor(conv_df$variable, levels=vns)

    ggplot(allDf, aes(x=run_idx, ymin=q5, y=median, ymax=q95)) +
    geom_errorbar(width=.1, , alpha=0.4) +
    geom_point(size=.5, alpha=0.8) + 
    geom_point(data=conv_df, aes(x=run_idx, y=-Inf), color="red", size=2.0, shape=4, inherit.aes=F) +
    geom_line(data=gt_df, aes(x=run_idx, y=value),color="red", inherit.aes=F) +
    facet_grid(rows = vars(variable), cols=vars(clock), scales="free_y", labeller = label_bquote(cols="Clock"==.(clock))) +
    theme_minimal()+
    labs(x="Run") +
    coord_cartesian(clip = 'off') +
    theme(
        axis.text.x=element_text(size=rel(0.7), angle = 45, hjust=1),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.grid.major = element_blank(), 
        axis.line = element_line(size=rel(0.2), colour = "grey80"),
        plot.title = element_text(hjust = 0.5,size=rel(1.0))) 
}

p1<-sum_plt(dfs)
pdf("../manuscript_figs/saturation.pdf",8,8)
plot(p1)
dev.off()
p1

```

```{r}
count_subs <- function(clock,run_idx)
{
    tr<-read.tree(paste0("./mut",clock,"/tree_clock_", run_idx, ".nwk"))
    exp_subs <- node.depth.edgelength(tr)[1:n_tips]
    out <- c(mean(exp_subs), run_idx, clock)
    names(out) <- c("exp_subs","run_idx", "clock")
    return(out)
}

subs_df <- data.frame(do.call(rbind,lapply(1L:mut_sets,
    function(i) do.call(rbind, lapply(1L:set_size,
            function(j) count_subs(i,j))))))

p2 <- ggplot(subs_df, aes(factor(clock), exp_subs/1e3L)) + 
    geom_violin() +
    theme_minimal() +
    labs(y="Expected Substitutions Per Site", x="Clock") + 
    theme(
        axis.text.x=element_text(size=rel(1.0), angle = 45, hjust=1),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.grid.major = element_blank(), 
        axis.line = element_line(size=rel(0.2), colour = "grey80"),
        plot.title = element_text(hjust = 0.5,size=rel(1.0)))
```

Plot Expected Number of Substitutions for Each Clock
```{r,out.width="100%"}
pdf("../manuscript_figs/saturation_exp_subs.pdf",8,8)
plot(p2)
dev.off()
p2
```