---
title: "Multimerger Timing Example"
output: rmarkdown::html_document
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4, tibble.print_max = 4)
```

Load Packages
```{r}
library(MMCTime)
library(ggplot2)
library(ape)
library(ggtree)
library(treeio)
library(dplyr)
library(posterior)
library(reshape2)
library(patchwork)
library(scales)

set.seed(2)
run_mcmc <- F
run_sim <- F
```
```{r}
sim_tre <- function(model, seed, ...)
{
    n_tips <- 200
    mu <- 1.0
    omega <- 1.0
    nsites <- 10000L

    samp_times <- 2020:2011
    n_samp <- as.vector(rmultinom(1, n_tips, rep(1/10, 10)))

    sim <- NA
    if (model == "km_beta")
    {
        sim <- simulate_km_beta(samp_times, n_samp, ...)
    }
    else if (model == "beta") 
    {
        sim <- simulate_beta(samp_times, n_samp, ...)
    } else if (model=="kingman") 
    {
        sim <- simulate_kingman(samp_times, n_samp, ...)
    } else 
    {
        stop("Unrecognised model")
    }

    phy_clock <- multi2di(sim$phy)
    phy_clock$edge.length <- sapply(phy_clock$edge.length, function (x) if(abs(x) < 1e-8) 0 else rgamma(1,shape = x * mu / omega, scale = omega))
    phy_clock$node.label <- NULL
    
    system(sprintf('mkdir tmp'))

    write.tree(phy_clock, "tmp/tree_clock.nwk")

    system(sprintf('cd tmp; seq-gen -l %d -s %f -m HKY -z %d < tree_clock.nwk > seqs.nex',nsites,1/nsites,seed))
    system(sprintf('cd tmp; iqtree -s seqs.nex -m HKY -seed %d -nt 1 -mem 4G', seed))

    phy_ml <- read.tree(paste0("tmp/seqs.nex.treefile"))
    phy_ml$edge.length <- phy_ml$edge.length*nsites

    system(sprintf('rm -r tmp'))

    return(list(dates=sim$dates, phy_gt=sim$phy, phy_clock=phy_clock, phy_ml=phy_ml))
}
```

Simulate a Genealogy From the Beta Coalescent
```{r, eval=run_sim}
sim_beta <- sim_tre("beta", 2, nu=1/12, alpha=0.5)
sim_kmb <- sim_tre("km_beta", 3, nu=1/12, alpha=0.2, phi=0.4)

saveRDS(sim_beta,"sim_beta.rds")
saveRDS(sim_kmb,"sim_kmb.rds")
```
```{r, eval=!run_sim}
sim_beta <- readRDS("sim_beta.rds")
sim_kmb <- readRDS("sim_kmb.rds")
```

Beta Trees
```{r}
p <- ggtree(sim_beta$phy_ml) + theme_tree2() + geom_tiplab(size=1.0)
pdf("../manuscript_figs/beta_ex_input.pdf", 8, 8)
p
dev.off()
p
```
Modified Beta Trees
```{r}
p <- ggtree(sim_kmb$phy_ml) + theme_tree2() + geom_tiplab(size=1.0)
pdf("../manuscript_figs/kmb_ex_input.pdf", 8, 8)
p
dev.off()
p
```

Run & Time Inference 
```{r}
time_phy <- function(sim, mod)
{
    phy <- sim$phy_ml
    n_tip <- length(phy$tip.label)
    pos <- sample(1:(n_tip - 2),1)
    outgroup <- ifelse(pos > n_tip, extract.clade(phy, pos)$tip.label, phy$tip.label[pos])
    phy <- root(phy,outgroup=outgroup, resolve.root=T)
    phy$edge.length <- round(phy$edge.length)

    res <- mmctime(phy, sim$dates, n_draws=1e3L, thin=2e3L, n_chain=4, model=mod, verbose=F)
    return(res)
}
```
```{r, eval=run_mcmc}
res_beta <- time_phy(sim_beta, "beta")
res_kmb <- time_phy(sim_kmb, "km_beta")
```
```{r, eval=run_mcmc}
saveRDS(res_beta, "res_beta.rds")
saveRDS(res_kmb, "res_kmb.rds")
```

```{r, eval=!run_mcmc}
res_beta <- readRDS("res_beta.rds")
res_kmb <- readRDS("res_kmb.rds")
```
```{r}
print(res_beta$summaries, n=20)
print(res_kmb$summaries, n=20)
```
```{r}
side_by_side <- function(sim, res)
{
    phy_gt <- sim$phy_gt
    mrsd <- max(sim$dates)
    n <- length(phy_gt$tip.label)
    m <- nrow(phy_gt$edge) - n + 1
    phy_gt <- di2multi(phy_gt)
    msize_node <- unname(c(rep(1,n),table(phy_gt$edge[,1])))
    msize_outgoing <- rep(F, n+m)

    for (i in 1:nrow(phy_gt$edge))
    {
        msize_outgoing[phy_gt$edge[i,2]] <- msize_node[phy_gt$edge[i,1]]
    }

    phy_gt.f <- fortify(as.phylo(phy_gt), layout="rectangular")

    max_x_gt <- max(phy_gt.f$x,na.rm=TRUE)
    phy_gt.f$x <- phy_gt.f$x - max_x_gt

    tip_ord_gt <- phy_gt.f %>%
                dplyr::filter(.data$isTip) %>%
                dplyr::arrange(.data$y) %>%
                dplyr::pull("label")

    phy_gt.tbl <- phy_gt.f %>% as_tibble %>% mutate(
        msize = msize_outgoing
    )

    plt_ci <- plot_densiCI(res,mrsd=mrsd, layout="rectangular", n_samp=100, tip.order=tip_ord_gt) + ggtitle("Densitree With CIs For Majority Clades") 

    plt_gt <- ggtree(tr=phy_gt.tbl, layout="rectangular", aes(color = msize>2)) + 
        scale_color_manual(values=c("red","blue")) +
        geom_tippoint(color="black", size=0.25) +
        ggtitle("Simulated Tree") +
        theme_tree2() +
        theme(legend.position="none",
            axis.text.x=element_text(angle = 45, hjust=1, size=4),
            panel.grid.major = element_blank(), 
            axis.line = element_line(size=rel(0.2), colour = "grey80"),
            plot.title = element_text(hjust = 0.5,size=6.0)) +
        scale_x_continuous(labels = label_math(expr=.x, format=function(x) mrsd + x))


    plt_gt | plt_ci
}
```
Beta side-by-side
```{r, eval=T, out.width="100%"}
p <- side_by_side(sim_beta, res_beta)
ggsave("../manuscript_figs/beta_ex_densi.png", plot=p, device = png, type="cairo", width=6, height=6, dpi=1000)
p
```
Modified Beta side-by-side
```{r, eval=T, out.width="100%"}
p <- side_by_side(sim_kmb, res_kmb)
ggsave("../manuscript_figs/kmb_ex_densi.png", plot=p, device = png, type="cairo", width=6, height=6, dpi=1000)
p
```
Beta posterior draws
```{r,eval=T,out.width="100%"}
p <- plot_mm_tree(sample_timetree(res_beta,9))
pdf("../manuscript_figs/beta_ex_ps.pdf", 8, 8)
p
dev.off()
p
```
Modified beta posterior draws
```{r,eval=T,out.width="100%"}
p <- plot_mm_tree(sample_timetree(res_kmb,9))
pdf("../manuscript_figs/kmb_ex_ps.pdf", 8, 8)
p
dev.off()
p
```
Beta traces
```{r,out.width="100%"}
p<-plot_traces(res_beta)
pdf("../manuscript_figs/beta_ex_traces.pdf", 8, 8)
p
dev.off()
p
```
Modified beta traces
```{r,out.width="100%"}
p<-plot_traces(res_kmb)
pdf("../manuscript_figs/kmb_ex_traces.pdf", 8, 8)
p
dev.off()
p
```
Beta pairs
```{r,out.width="100%"}
p<-plot_pars(res_beta)
pdf("../manuscript_figs/beta_ex_pars.pdf", 8, 8)
p
dev.off()
p
```
Modified beta pairs
```{r,out.width="100%"}
p<-plot_pars(res_kmb)
pdf("../manuscript_figs/kmb_ex_pars.pdf", 8, 8)
p
dev.off()
p
```