---
title: "Multimerger Case Study: MTB Sequences from Menardo2019"
output: rmarkdown::html_document
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 4, tibble.print_max = 4)
```

Load Packages
```{r}
library(MMCTime)
library(ggplot2)
library(ape)
library(ggtree)
library(posterior)
library(patchwork)
library(reshape2)
library(dplyr)
set.seed(1234356)
```

```{r}
name_vec <- c("Eldholm2015", "Lee2015", "Bainomugisa2018")
tree_names <- c("Eldholm2015", "Lee2015", "Bainomugisa2018")
in_names <- paste0("ml_trees/",tree_names, ".fasta.ml_tree.nwk")
tres <- lapply(in_names, read.tree)

names(tres) <- tree_names
class(tres) <- "multiPhylo"

supp <- read.delim("menardo_supplementary_table1.txt", header=T, sep = "\t")
dates_tab <- supp[,c("Genome.name","Year.of.sampling")]
rownames(dates_tab) <- dates_tab[,"Genome.name"]

dates_tab$Year.of.sampling <- as.numeric(dates_tab$Year.of.sampling)
```
Plot ML trees
```{r, out.width="100%"}
p <- ggtree(tres) + theme_tree2() + theme_minimal() + facet_wrap(~.id, ncol=3) +
theme(
    axis.text.x=element_text(angle = 45, hjust=1),
    axis.text.y = element_blank(),
    plot.margin = margin(0, 0, 0, 0, "cm"),
    panel.grid.major = element_blank(), 
    axis.line = element_line(size=rel(0.2), colour = "grey80"),
    plot.title = element_text(hjust = 0.5,size=rel(1.0))
)
pdf("../manuscript_figs/mtb_ml_trees.pdf",8,8)
p
dev.off()
p
```

Load run results
```{r}
res_beta <- lapply(name_vec, function(s) readRDS(paste0("analysis_out/",s,"_beta.rds")))
names(res_beta) <- name_vec
res_kmb <- lapply(name_vec, function(s) readRDS(paste0("analysis_out/",s,"_km_beta.rds")))
names(res_kmb) <- name_vec
res_kingman <- lapply(name_vec, function(s) readRDS(paste0("analysis_out/",s,"_kingman.rds")))
names(res_kingman) <- name_vec
```

Build DataFrames
```{r}
foo <- function(x,vnames) do.call(rbind,lapply(names(x), function(s) cbind(x[[s]]$draws[,vnames],dataset=s)))
df_beta <- foo(res_beta,c("alpha","nu","mu","omega"))
df_kmb <- foo(res_kmb,c("phi","alpha","nu","mu","omega"))
df_kingman <- foo(res_kingman,c("nu","mu","omega"))
```

Plot clock parameters
```{r,out.width="100%"}
mut_df <- rbind(cbind(df_beta[,c("mu", "omega", "dataset")], model="Beta"),
    cbind(df_kmb[,c("mu", "omega", "dataset")], model="Extended beta"),
    cbind(df_kingman[,c("mu", "omega", "dataset")], model="Kingman"))
mDf <- melt(mut_df, measure.vars=c("mu","omega"))
mDf$model <- factor(mDf$model, levels=c("Kingman","Beta", "Extended beta"))
qDf<-mDf %>% group_by(model, dataset, variable) %>%
    summarize(lower=quantile(value,probs=0.025),
    med=quantile(value,probs=0.5),
    upper=quantile(value,probs=0.975))
p <- ggplot(qDf, aes(x=model,color=model)) + 
    geom_linerange(aes(ymin=lower, ymax=upper),lwd=0.5) +
    geom_point(aes(y=med),size=1.5) +
    labs(y="") +
    facet_grid(rows=vars(variable), cols=vars(dataset),scales="free_y") +
    theme_minimal()+
    theme(
        axis.text.x=element_text(angle = 45, hjust=1),
        plot.margin = margin(0, 0, 0, 0, "cm"),
        panel.grid.major = element_blank(), 
        axis.line = element_line(size=rel(0.2), colour = "grey80"),
        plot.title = element_text(hjust = 0.5,size=rel(1.0))
    )
pdf("../manuscript_figs/mtb_clock.pdf",8,8)
p
dev.off()
p
```

Plot coalescent parameters
```{r,out.width="100%"}
df1 <- melt(cbind(df_beta[,c("nu", "alpha", "dataset")], model="Beta"),measure.vars=c("nu", "alpha"))
df2 <- melt(cbind(df_kmb[,c("nu", "alpha", "phi","dataset")], model="Extended beta"),measure.vars=c("nu", "alpha", "phi"))


p <- rbind(df1,df2) %>% group_by(model, dataset, variable) %>%
    summarize(lower=quantile(value,probs=0.025),
    med=quantile(value,probs=0.5),
    upper=quantile(value,probs=0.975)) %>%
    ggplot(., aes(y=med, ymin=lower, ymax=upper, x=model, color=model)) +
        geom_linerange(lwd=0.5) +
        geom_point(size=1.5) +
        facet_grid(rows=vars(variable), cols=vars(dataset),scales="free_y") +
        labs(y="") +
        theme_minimal()+
        theme(
            axis.text.x=element_text(angle = 45, hjust=1),
            plot.margin = margin(0, 0, 0, 0, "cm"),
            panel.grid.major = element_blank(), 
            axis.line = element_line(size=rel(0.2), colour = "grey80"),
            plot.title = element_text(hjust = 0.5,size=rel(1.0))
        )

pdf("../manuscript_figs/mtb_coal.pdf",8,8)
p
dev.off()
p
```

Show densitrees for Eldholm2015
```{r,out.width="100%"}
mrsd_eldholm <- max(dates_tab[res_beta[["Eldholm2015"]]$undated$tip.label,"Year.of.sampling"],na.rm=T)

p1 <- plot_densiCI(res_beta[["Eldholm2015"]], n_samp=100, mrsd=mrsd_eldholm,layout="rectangular") +
    ggtitle("Beta")
p2 <- plot_densiCI(res_kmb[["Eldholm2015"]], n_samp=100, mrsd=mrsd_eldholm,layout="rectangular") +
    ggtitle("Extended Beta")
p3 <- plot_densiCI(res_kingman[["Eldholm2015"]], n_samp=100, mrsd=mrsd_eldholm,layout="rectangular") +
    ggtitle("Kingman")
p3 <- p3 + (p3$theme %+replace% theme(legend.position="none"))

p <- (p1 | p2 | p3) + plot_layout(guides = "collect")
ggsave("../manuscript_figs/mtb_densi.png", plot=p, device = png, type="cairo", width=6, height=6, dpi=1000)
p
```
Show Posterior Samples for Eldholm2015
```{r,out.width="100%"}
p <- plot_mm_tree(sample_timetree(res_kmb[["Eldholm2015"]],9)) + ggtitle("Extended Beta")
pdf("../manuscript_figs/mtb_ps_kmb.pdf", 8, 8)
p
dev.off()
p

p <- plot_mm_tree(sample_timetree(res_beta[["Eldholm2015"]],9)) + ggtitle("Beta")
pdf("../manuscript_figs/mtb_ps_beta.pdf", 8, 8)
p
dev.off()
p

p <- plot_mm_tree(sample_timetree(res_kingman[["Eldholm2015"]],9)) + ggtitle("Kingman")
pdf("../manuscript_figs/mtb_ps_kingman.pdf", 8, 8)
p
dev.off()
p

```